[workspace]
members = ["projects/*"]
default-members = [
    "projects/font-fill",
    "projects/font-fill-cli",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
