[workspace]
members = ["projects/*"]
default-members = [
    "projects/fill-fonts",
    "projects/sycamore-event",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
