version = "Two"
edition = "2018"
max_width = 144
comment_width = 100

imports_granularity="Crate"
use_small_heuristics = "Max"
control_brace_style = "ClosingNextLine"
wrap_comments = true
normalize_comments = true
format_code_in_doc_comments = true